### ISSUE TITLE
[BUG]TypeError: view.save is not a function

### ISSUE THREAD

**Issue by BenAngel65** [dy-sh/obsidian-consistent-attachments-and-links#118]
plugin:consistent-at…ents-and-links:4578 Uncaught (in promise) TypeError: view.save is not a function
    at ConsistentAttachmentsAndLinksPlugin.saveAllOpenNotes (plugin:consistent-at…s-and-links:4578:18)
    at ConsistentAttachmentsAndLinksPlugin.reorganizeVault (plugin:consistent-at…s-and-links:4550:16)
    at Object.callback (plugin:consistent-at…s-and-links:4269:28)
    at OK (app.js:1:2117674)
    at t.onChooseItem (app.js:1:2726336)
    at t.onChooseSuggestion (app.js:1:1760272)
    at t.selectSuggestion (app.js:1:1759742)
    at e.useSelectedItem (app.js:1:1433276)
    at Object.func (app.js:1:1430675)
    at e.handleKey (app.js:1:754496)

---
None of any features can be used

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.21.5
